services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: adiev
      POSTGRES_DB: sales_management

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: api
    image: adiev/salesapi:latest
    restart: always
    ports:
      - 8088:8088
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/sales_management
      ACTIVE_PROFILE: dev
